compatibility_date = "2023-02-11"
name = "transformation-durable_objects"
main = "./index.mjs"

[vars]
DEBUG = "blueprint:*"

[durable_objects]
bindings = [
  {name = "DO_API", class_name = "DurableAPI"},
]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Counter"]

[[migrations]]
tag = "v2"
new_classes = ["PreviewCounter"]

[[migrations]]
tag = "v3"
new_classes = ["TemporalEntity"]

[[migrations]]
tag = "v4"
new_classes = ["Tree"]

[[migrations]]
tag = "v5"
deleted_classes = ["PreviewCounter", "Counter", "TemporalEntity", "Tree"]

[[migrations]]
tag = "v6"
new_classes = ["DurableAPI"]

[[migrations]]
tag = "v7"
new_classes = ["Greeter"]

[[migrations]]
tag = "v8"
deleted_classes = ["Greeter", "Counter"]
