compatibility_date = "2022-12-20"

name = "transformation-durable_objects"
# type = "javascript" is required to use the `[build]` section
type = "javascript"
workers_dev = true

[build.upload]
# Upload the code directly from the src directory.
dir = "./"
# The "modules" upload format is required for all projects that export a Durable Objects class
format = "modules"
main = "./index.mjs"

[durable_objects]
bindings = [
  {name = "COUNTER", class_name = "Counter"},
  # {name = "COUNTER", class_name = "PreviewCounter"},
  {name = "TEMPORAL_ENTITY", class_name = "TemporalEntity"},
  {name = "TREE", class_name = "Tree"},
]

[[migrations]]
tag = "v1"
new_classes = ["Counter"]

[[migrations]]
tag = "v2"
new_classes = ["PreviewCounter"]

[[migrations]]
tag = "v3"
new_classes = ["TemporalEntity"]

[[migrations]]
tag = "v4"
new_classes = ["Tree"]
