compatibility_date = "2023-02-11"
name = "transformation-durable_objects"
# type = "javascript"
main = "index.mjs"

[durable_objects]
bindings = [
  {name = "COUNTER", class_name = "Counter"},
  {name = "TEMPORAL_ENTITY", class_name = "TemporalEntity"},
  {name = "TREE", class_name = "Tree"},
]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Counter"]

[[migrations]]
tag = "v2"
new_classes = ["PreviewCounter"]

[[migrations]]
tag = "v3"
new_classes = ["TemporalEntity"]

[[migrations]]
tag = "v4"
new_classes = ["Tree"]
