name: Coverage Set Baseline

on:
  pull_request_target:
    types:
      - closed

jobs:
  coverage-set-baseline:
    if: github.event.pull_request_target.merged == true
    uses: ./.github/workflows/coverage.yml