name: Test in Cloudflare

on:
  - pull_request

jobs:
  test-in-cloudflare:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [17.x]
        os: [ubuntu-latest]

    env:
      CYPRESS_BASE_URL: "${{ format('https://{0}.transformation.pages.dev', github.head_ref) }}"
      BRANCH_VERSION_CHECK_URL: "${{ format('https://{0}.transformation.pages.dev/api/version/{1}', github.head_ref, github.event.after) }}"

    steps:

    # - name: Dump GitHub context
    #   env:
    #     GITHUB_CONTEXT: ${{ toJson(github) }}
    #   run: echo "$GITHUB_CONTEXT"

    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm ci
      run: |
        npm ci
      env:
        CI: true

    - name: Wait for Cloudflare deploy of correct version
      uses: cygnetdigital/wait_for_response@v2.0.0
      with:
        url: ${{ env.BRANCH_VERSION_CHECK_URL }}
        responseCode: '200'
        timeout: 360000
        interval: 5000

    - name: Cypress run
      env:
        CI: true
        SENDGRID_LOGIN: ${{ secrets.SENDGRID_LOGIN }}
        TESTING_OVERRIDE_CODE: ${{ secrets.TESTING_OVERRIDE_CODE }}
      run: |
       npm run cypress:run
    
    - name: Upload screenshots
      uses: actions/upload-artifact@v3
      if: ${{ always() }}
      with:
        name: test-in-cloudflare-screenshots
        path: cypress/screenshots
