name: Test in Cloudflare

on:
  - pull_request

jobs:
  test-in-cloudflare:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [17.x]
        os: [ubuntu-latest]

    env:
      JUNK: ${{ format('something: {1}', 'foo') }}
    #   BRANCH_VERSION_URL: ${{ format('https://{0}.transformation.pages.dev/api/version', env.GITHUB_HEAD_REF) }}

    steps:
    - uses: actions/checkout@v2

    - name: Version BEFORE deploy
      run: |
        echo $JUNK
    #     echo $BRANCH_VERSION_URL
    #     curl -I $BRANCH_VERSION_URL

    # - name: Wait for Cloudflare deploy
    #   uses: cygnetdigital/wait_for_response@v2.0.0
    #   # env:
    #   #   GITHUB_CONTEXT: ${{ toJson(github) }}
    #   with:
    #     # url: 'http://localhost:8788/api/version/$GITHUB_CONTEX'
    #     url: format('https://{0}.transformation.pages.dev/api/version/{2}', $GITHUB_HEAD_REF, ${{ github.event.pull_request.head.sha }})
    #     responseCode: '200'
    #     timeout: 180000
    #     interval: 5000

    # - name: Await CF Pages
    #   uses: WalshyDev/cf-pages-await@v1.1.0
    #   with:
    #     accountEmail: ${{ secrets.CF_ACCOUNT_EMAIL  }}
    #     apiKey: ${{ secrets.CF_API_KEY  }}
    #     accountId: ${{ secrets.CF_ACCOUNT_ID  }}
    #     project: 'transformation'
    #     githubToken: ${{ secrets.GITHUB_TOKEN }}

    # - name: Version AFTER deploy
    #   run: |
    #     curl -I $BRANCH_VERSION_URL

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm ci
      run: |
        npm ci
      env:
        CI: true

    - name: npm test
      run: |
        npm run test
      env:
        CI: true
